### ISSUE TITLE
NOT working with ruby 2.2.0

### ISSUE THREAD

**Issue by wangqiang1208** [ledermann/rails-settings#63]
With latest gem 2.3.0, rails 4.1.8, ruby 2.2.0, I saw this errors:

<code>rails g rails_settings:migration</code>
<code>Could not find generator rails_settings:migration</code>

<code>NoMethodError: undefined method `has_settings' for User (call 'User.connection' to establish a connection):Class</code>

However, when I do <code> rvm use 2.1.2 </code>, everything works fine.

**Comment by scottrobertson** [comment]
@allenwq why did you close this? DId you find a fix? I have the same issue

**Comment by allenwq** [comment]
@scottrobertson Somehow it suddenly works.. I haven't got time to figure out the reason yet.
